version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: YLAB_HW
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/YLAB_HW
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=12345

volumes:
  postgres-data:
