version: '3.8'

services:
  db:
    image: postgres:13
    container_name: YLABHW
    environment:
      POSTGRES_DB: YLAB_HW
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - test_network

volumes:
  postgres_data:

networks:
  test_network:
    driver: bridge
